DROP TABLE IF EXISTS CRASHTIME_PER_COUNTY;

CREATE TABLE CRASHTIME_PER_COUNTY (
  COUNTY TEXT,
  HOUR INTEGER,
  `2019` INTEGER,
  `2020` INTEGER,
  `2021` INTEGER,
  COLLISION_COUNT INTEGER
);

INSERT INTO CRASHTIME_PER_COUNTY (COUNTY, HOUR, `2019`, `2020`, `2021`, COLLISION_COUNT)
SELECT COUNTY, 
cast(substr(CRASHTIME, 1, 2) as int) as HOUR,
sum(case when substr(CRASHDATE, 7) = '2019' then 1 else 0 end) as `2019`,
sum(case when substr(CRASHDATE, 7) = '2020' then 1 else 0 end) as `2020`,
sum(case when substr(CRASHDATE, 7) = '2021' then 1 else 0 end) as `2021`,
count(COLLISION_ID) as COLLISION_COUNT
FROM CONSOLIDATED
WHERE COUNTY IS NOT NULL AND CRASHDATE IS NOT NULL AND CRASHTIME IS NOT NULL
GROUP BY COUNTY, cast(substr(CRASHTIME, 1, 2) as int)
ORDER BY COUNTY, HOUR;

SELECT * FROM CRASHTIME_PER_COUNTY;