DROP TABLE IF EXISTS PERSON_2NF;
DROP TABLE IF EXISTS VEHICLE_2NF;
DROP TABLE IF EXISTS CRASH_2NF;


CREATE TABLE CRASH_2NF (
  COLLISION_ID INTEGER PRIMARY KEY,
  CRASHDATE DATE,
  CRASHTIME TIME,
  CRASHDATETIME DATETIME,
  BOROUGH TEXT,
  COUNTY TEXT,
  STATE TEXT,
  ZIPCODE TEXT,
  LATITUDE REAL,
  LONGITUDE REAL
);


CREATE TABLE VEHICLE_2NF (
  VEHICLE_ID INTEGER PRIMARY KEY,
  COLLISION_ID INTEGER,
  STATE_REGISTRATION TEXT,
  VEHICLE_CATEGORY TEXT,
  VEHICLE_YEAR INTEGER,
  DRIVER_LICENSE_STATUS TEXT,
  DRIVER_LICENSE_JURISDICTION TEXT,
  PRIMARY_CONTRIBUTING_FACTOR TEXT,
	FOREIGN KEY (COLLISION_ID) REFERENCES CRASH_2NF(COLLISION_ID)
);


CREATE TABLE PERSON_2NF (
  PERSON_ID INTEGER PRIMARY KEY,
  COLLISION_ID INTEGER,
  PERSON_TYPE TEXT,
  PERSON_ROLE TEXT,
  PERSON_AGE INTEGER,
  PERSON_SEX TEXT,
  PERSON_INJURY TEXT,
  VEHICLE_ID INTEGER,
  SAFETY_EQUIPMENT TEXT,
	FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE_2NF(VEHICLE_ID),
	FOREIGN KEY (COLLISION_ID) REFERENCES CRASH_2NF(COLLISION_ID)
);


INSERT INTO CRASH_2NF
SELECT *
FROM CRASH_1NF;



INSERT INTO VEHICLE_2NF
SELECT *
FROM VEHICLE_1NF
WHERE COLLISION_ID IN (SELECT COLLISION_ID FROM CRASH_2NF);


INSERT INTO PERSON_2NF
SELECT *
FROM PERSON_1NF
WHERE COLLISION_ID IN (SELECT COLLISION_ID FROM CRASH_2NF)
AND VEHICLE_ID IN (SELECT VEHICLE_ID FROM VEHICLE_2NF);


