-- Drop VEHICLE_1NF table if it exists
DROP TABLE IF EXISTS VEHICLE_1NF;

-- Create VEHICLE_1NF table with required columns
CREATE TABLE VEHICLE_1NF (
  VEHICLE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  COLLISION_ID INTEGER,
  STATE_REGISTRATION TEXT,
  VEHICLE_CATEGORY TEXT,
  VEHICLE_YEAR INTEGER,
  DRIVER_LICENSE_STATUS TEXT,
  DRIVER_LICENSE_JURISDICTION TEXT,
  PRIMARY_CONTRIBUTING_FACTOR TEXT
);

  -- Insert data into VEHICLE_1NF table based on specified filters
INSERT OR IGNORE INTO VEHICLE_1NF (VEHICLE_ID, COLLISION_ID, STATE_REGISTRATION, VEHICLE_CATEGORY, VEHICLE_YEAR, DRIVER_LICENSE_STATUS, DRIVER_LICENSE_JURISDICTION, PRIMARY_CONTRIBUTING_FACTOR)
SELECT DISTINCT
  A.UNIQUE_ID AS VEHICLE_ID,
  A.COLLISION_ID,
  A.STATE_REGISTRATION,
  B.VEHICLE_CATEGORY,
  A.VEHICLE_YEAR,
  A.DRIVER_LICENSE_STATUS,
  A.DRIVER_LICENSE_JURISDICTION,
  CASE 
    WHEN CONTRIBUTING_FACTOR_1 IS NULL THEN 'Unspecified'
    ELSE CONTRIBUTING_FACTOR_1 
  END AS PRIMARY_CONTRIBUTING_FACTOR
FROM 
  VEHICLE_0NF A
  INNER JOIN VEHICLE_TYPE_TO_CATEGORY B ON A.VEHICLE_TYPE = B.VEHICLE_TYPE
WHERE 
  VEHICLE_CATEGORY IS NOT NULL;
