DROP TABLE IF EXISTS CONSOLIDATED;

CREATE TABLE CONSOLIDATED AS
SELECT 
P.*,
V.STATE_REGISTRATION,	
V.VEHICLE_CATEGORY,	
V.VEHICLE_YEAR,	
V.DRIVER_LICENSE_STATUS,	
V.DRIVER_LICENSE_JURISDICTION,	
V.PRIMARY_CONTRIBUTING_FACTOR,
C.COLLISION_ID,	
C.CRASHDATE,	
C.CRASHTIME,	
C.BOROUGH,	
C.COUNTY,	
C.STATE,	
C.ZIPCODE,	
C.LATITUDE,	
C.LONGITUDE
FROM PERSON_2NF P 
LEFT JOIN VEHICLE_2NF V  ON P.VEHICLE_ID=V.VEHICLE_ID
LEFT JOIN CRASH_2NF C ON C.COLLISION_ID=P.COLLISION_ID AND C.COLLISION_ID=V.COLLISION_ID

    