DROP TABLE IF EXISTS PERSON_INJURED_BY_SEX;

CREATE TABLE PERSON_INJURED_BY_SEX (
    PERSON_INJURY TEXT,
    PERSON_SEX TEXT,
    BRONX INTEGER,
    BROOKLYN INTEGER,
    MANHATTAN INTEGER,
    QUEENS INTEGER,
    "STATEN ISLAND" INTEGER,
    "Grand Total" INTEGER
);

INSERT INTO PERSON_INJURED_BY_SEX (
    PERSON_INJURY,
    PERSON_SEX,
    BRONX,
    BROOKLYN,
    MANHATTAN,
    QUEENS,
    "STATEN ISLAND",
    "Grand Total"
)
SELECT PERSON_INJURY, PERSON_SEX,
    SUM(CASE WHEN BOROUGH = 'BRONX' THEN COLLISION_COUNT ELSE 0 END) AS BRONX,
    SUM(CASE WHEN BOROUGH = 'BROOKLYN' THEN COLLISION_COUNT ELSE 0 END) AS BROOKLYN,
    SUM(CASE WHEN BOROUGH = 'MANHATTAN' THEN COLLISION_COUNT ELSE 0 END) AS MANHATTAN,
    SUM(CASE WHEN BOROUGH = 'QUEENS' THEN COLLISION_COUNT ELSE 0 END) AS QUEENS,
    SUM(CASE WHEN BOROUGH = 'STATEN ISLAND' THEN COLLISION_COUNT ELSE 0 END) AS "STATEN ISLAND",
    SUM(COLLISION_COUNT) AS "Grand Total"
FROM (
    SELECT PERSON_INJURY, PERSON_SEX, BOROUGH, COUNT(COLLISION_ID) AS COLLISION_COUNT
    FROM CONSOLIDATED
    WHERE PERSON_INJURY IN ('Killed', 'Injured') AND PERSON_SEX IN ('F', 'M')
    GROUP BY PERSON_INJURY, PERSON_SEX, BOROUGH
) AS subquery
GROUP BY PERSON_INJURY, PERSON_SEX

UNION

SELECT 'Grand Total', NULL,
    SUM(CASE WHEN BOROUGH = 'BRONX' THEN COLLISION_COUNT ELSE 0 END) AS BRONX,
    SUM(CASE WHEN BOROUGH = 'BROOKLYN' THEN COLLISION_COUNT ELSE 0 END) AS BROOKLYN,
    SUM(CASE WHEN BOROUGH = 'MANHATTAN' THEN COLLISION_COUNT ELSE 0 END) AS MANHATTAN,
    SUM(CASE WHEN BOROUGH = 'QUEENS' THEN COLLISION_COUNT ELSE 0 END) AS QUEENS,
    SUM(CASE WHEN BOROUGH = 'STATEN ISLAND' THEN COLLISION_COUNT ELSE 0 END) AS "STATEN ISLAND",
    SUM(COLLISION_COUNT) AS "Grand Total"
FROM (
    SELECT PERSON_INJURY, PERSON_SEX, BOROUGH, COUNT(COLLISION_ID) AS COLLISION_COUNT
    FROM CONSOLIDATED
    WHERE PERSON_INJURY IN ('Killed', 'Injured') AND PERSON_SEX IN ('F', 'M')
    GROUP BY PERSON_INJURY, PERSON_SEX, BOROUGH
) AS subquery
GROUP BY 1
ORDER BY 1 DESC, 2 ASC;


Select * FROM PERSON_INJURED_BY_SEX